### PR TITLE
Add a COMMIT_BODY option

### PR DESCRIPTION
**Pull request by grahammcculloch**
Some GitHub actions can check for specific content in a commit message's body. For example a versionbot that checks for content like `Change-type: patch`.

This change allows the calling workflow to specify a string to use as the commit body. This string will be appended to the commit message, separated by two new lines.

Change-type: minor
Signed-off-by: Graham McCulloch <graham@balena.io>

### CODE REVIEW

**Comment by BetaHuhn** [comment]
Hey @grahammcculloch,

Thank you so much for taking the time to contribute to this action and for creating this great PR!

If you could add an example to the README on how to use this option, then I would be even happier. I will merge this after that and release a new version of the action asap.

**Comment by grahammcculloch** [comment]
@BetaHuhn sure thing - just added an example to the README. Hope it's suitable?

**Comment by BetaHuhn** [comment]
Yes that works. Thanks so much!

Will merge it this evening.

**Comment by BetaHuhn** [comment]
Thanks again!

**Comment by grahammcculloch** [comment]
Thanks for your quick merging of this PR @BetaHuhn - it's unblocked us on using this excellent GitHub action! Much appreciated.

**Pull request merged**
