### PR TITLE
Add support for compiling Jinja-style templates in sync process

### PR DESCRIPTION
**Pull request by dhruvkb**
Sometimes a single file must be synced to different repositories with small differences. This PR allows files to be marked as templates which are then rendered using Nunjucks instead of simply being copied over as-is.

### CODE REVIEW

**Comment by BetaHuhn** [comment]
Hey @dhruvkb, thanks for taking the time to create this PR!

I wanted to add support for templates for a while (https://github.com/BetaHuhn/repo-file-sync-action/discussions/204) but never had the time to work on it so far.

Any specific reasons for going with Nunjucks as the template engine instead of others like [mustache](https://mustache.github.io/), [Handlebars](https://handlebarsjs.com/) or one of the many others?

**Comment by dhruvkb** [comment]
@BetaHuhn is something needed from my end to get this PR merged? We'd like to use templates in our repos so we're eagerly looking forward to a release that includes this feature.

**Comment by BetaHuhn** [comment]
> To be honest, it was largely a subjective choice. I come from a Python background where Jinja is like the gold standard so Nunjucks made sense. If you have a strong preference for an alternative template engine...

Makes sense. No strong opinions on my side, was just curious :)

> Is something needed from my end to get this PR merged?

@dhruvkb No, was just too busy to actually review the changes. Will take a look now.

**Review by BetaHuhn — APPROVED** [review]
Updated the README to make it easier for people not familiar with Jinja or Nunjucks. Otherwise everything looks good.

Thanks again for the PR!

**Pull request merged**
