### PR TITLE
Add possibility to exclude subfolders from synced folders

### PR DESCRIPTION
**Pull request by maikenp**
If a folder is included in the sync list, it is currently only possible to exclude specific files in that folder.
It would be useful to be able to exclude all the contents of subfolders of the folder to be synced.

This enhancement is an attempt to allow subfolders with all their contents to be excluded.

### CODE REVIEW

**Comment by BetaHuhn** [comment]
Thanks for the PR @maikenp!

Could you please fix the merge conflicts?

**Comment by maikenp** [comment]
Thanks a lot, will do that and ask questions if I am unsure about how to resolve.

**Comment by maikenp** [comment]
Is this PR now in the correct state? I lost a bit track of the correct procedure for building etc.

**Review by BetaHuhn — APPROVED** [review]
Thanks!

**Pull request merged**
